export const suppliersTypes = {
  REGISTER_SUPPLIER_REQUEST: "./suppliers/REGISTER_SUPPLIER_REQUEST",
  REGISTER_SUPPLIER_SUCCESS: "./suppliers/REGISTER_SUPPLIER_SUCCESS",
  REGISTER_SUPPLIER_FAILURE: "./suppliers/REGISTER_SUPPLIER_FAILURE",
};
