export const ordersTypes = {
  GET_ORDER_LIST_REQUEST: "./customers/GET_ORDER_LIST_REQUEST",
  GET_ORDER_LIST_SUCCESS: "./customers/GET_ORDER_LIST_SUCCESS",
  GET_ORDER_LIST_FAILURE: "./customers/GET_ORDER_LIST_FAILURE",

  GET_ORDER_BY_ID_REQUEST: "./customers/GET_ORDER_BY_ID_REQUEST",
  GET_ORDER_BY_ID_SUCCESS: "./customers/GET_ORDER_BY_ID_SUCCESS",
  GET_ORDER_BY_ID_FAILURE: "./customers/GET_ORDER_BY_ID_FAILURE",
  GET_ORDER_BY_ID_CLEAN: "./customers/GET_ORDER_BY_ID_CLEAN",

  REGISTER_ORDER_REQUEST: "./customers/REGISTER_ORDER_REQUEST",
  REGISTER_ORDER_SUCCESS: "./customers/REGISTER_ORDER_SUCCESS",
  REGISTER_ORDER_FAILURE: "./customers/REGISTER_ORDER_FAILURE",

  EDIT_ORDER_REQUEST: "./customers/EDIT_ORDER_REQUEST",
  EDIT_ORDER_SUCCESS: "./customers/EDIT_ORDER_SUCCESS",
  EDIT_ORDER_FAILURE: "./customers/EDIT_ORDER_FAILURE",
};
